channels:
  - conda-forge
dependencies:
  - aiohttp>=3.10.2
  - botocore<1.36
  - configobj
  - defusedxml
  - netifaces
  - numpy
  - pip
  - pip:
    - posttroll==1.12.1
    - pyorbital==1.9.2
    - pytroll-collectors==0.17.0
    - pytroll-schedule==0.7.1
  - pyresample==1.33.0
  - python=3.12
  - pyyaml
  - pyzmq
  - requests>=2.32.0
  - s3fs>=2022.8.2
  - scipy
  - trollsift=0.5.1
  - urllib3>=2.2.2
  - watchdog
  - zeromq!=4.0.0
